// antd v3 图标 type 名 → @ant-design/icons 具名组件映射。
// 仅收录代码中动态使用的名字（PROJECT_ICON 面板、ErrMsg 等场景），
// 静态 <Icon type="xxx"/> 应直接用具名组件，不走此表。
// v3 的 `-o` 系列在 v4 对应 Outlined 线框版；其余常用名对照官方 v4 迁移表。
import {
  CodeOutlined,
  SwapOutlined,
  ClockCircleOutlined,
  UnlockOutlined,
  CalendarOutlined,
  PlayCircleOutlined,
  FileTextOutlined,
  DesktopOutlined,
  HddOutlined,
  AppstoreOutlined,
  LineChartOutlined,
  MailOutlined,
  MobileOutlined,
  NotificationOutlined,
  PictureOutlined,
  PoweroffOutlined,
  SearchOutlined,
  SettingOutlined,
  ShareAltOutlined,
  ShoppingCartOutlined,
  TagOutlined,
  VideoCameraOutlined,
  CloudOutlined,
  StarOutlined,
  EnvironmentOutlined,
  CameraOutlined,
  TeamOutlined,
  CustomerServiceOutlined,
  PayCircleOutlined,
  RocketOutlined,
  DatabaseOutlined,
  ToolOutlined,
  WifiOutlined,
  IdcardOutlined,
  MedicineBoxOutlined,
  CoffeeOutlined,
  SafetyOutlined,
  GlobalOutlined,
  ApiOutlined,
  ForkOutlined,
  AndroidOutlined,
  AppleOutlined,
  QuestionCircleOutlined,
  CheckOutlined,
  DeleteOutlined,
  PlusOutlined,
  EyeOutlined,
  EditOutlined,
  CloseOutlined,
  DownloadOutlined,
  UploadOutlined,
  CopyOutlined,
  GithubOutlined,
  AliwangwangOutlined
} from '@ant-design/icons';

export const V3_TO_V4_ICON = {
  'code-o': CodeOutlined,
  swap: SwapOutlined,
  'clock-circle-o': ClockCircleOutlined,
  unlock: UnlockOutlined,
  calendar: CalendarOutlined,
  'play-circle-o': PlayCircleOutlined,
  'file-text': FileTextOutlined,
  desktop: DesktopOutlined,
  hdd: HddOutlined,
  'appstore-o': AppstoreOutlined,
  'line-chart': LineChartOutlined,
  mail: MailOutlined,
  mobile: MobileOutlined,
  notification: NotificationOutlined,
  picture: PictureOutlined,
  poweroff: PoweroffOutlined,
  search: SearchOutlined,
  setting: SettingOutlined,
  'share-alt': ShareAltOutlined,
  'shopping-cart': ShoppingCartOutlined,
  'tag-o': TagOutlined,
  'video-camera': VideoCameraOutlined,
  'cloud-o': CloudOutlined,
  'star-o': StarOutlined,
  'environment-o': EnvironmentOutlined,
  'camera-o': CameraOutlined,
  team: TeamOutlined,
  'customer-service': CustomerServiceOutlined,
  'pay-circle-o': PayCircleOutlined,
  rocket: RocketOutlined,
  database: DatabaseOutlined,
  tool: ToolOutlined,
  wifi: WifiOutlined,
  idcard: IdcardOutlined,
  'medicine-box': MedicineBoxOutlined,
  coffee: CoffeeOutlined,
  safety: SafetyOutlined,
  global: GlobalOutlined,
  api: ApiOutlined,
  fork: ForkOutlined,
  'android-o': AndroidOutlined,
  'apple-o': AppleOutlined,
  // 项目内其余动态场景的常用补充
  'question-circle-o': QuestionCircleOutlined,
  check: CheckOutlined,
  delete: DeleteOutlined,
  plus: PlusOutlined,
  'eye-o': EyeOutlined,
  edit: EditOutlined,
  close: CloseOutlined,
  'download': DownloadOutlined,
  upload: UploadOutlined,
  copy: CopyOutlined,
  github: GithubOutlined,
  'aliwangwang-o': AliwangwangOutlined,
  aliwangwang: AliwangwangOutlined
};

/**
 * 按 v3 图标名取 v4 具名图标组件；未知名字回落到星标（与旧默认 star-o 对应）。
 * @param {string} v3Name
 * @returns {React.ComponentType<any>}
 */
export function getV4Icon(v3Name) {
  return V3_TO_V4_ICON[v3Name] || StarOutlined;
}
